import { useState } from 'react';
import axios from 'axios';
import { useNavigate } from 'react-router-dom';
import { GoogleLogin } from '@react-oauth/google';

const Login = () => {

    const [formData, setFormData] = useState({ email: '', password: '' });
  const navigate = useNavigate();

  const handleGoogleSuccess = async (credentialResponse) => {
    try {
      // credentialResponse.credential is a secure JWT token generated by Google
      const idToken = credentialResponse.credential;

      // Send this token to your backend for validation and login/signup
      const res = await axios.post('http://localhost:4999/api/auth/google', { token: idToken });
      
      // Save your app's custom JWT token to localStorage just like manual login
      localStorage.setItem('token', res.data.token);
      
      // Redirect straight to dashboard
      navigate('/dashboard');
    } catch (err) {
      console.error("Google Authentication Failed on Backend", err);
    }
  };

  return (
    <div className="flex flex-col items-center justify-center h-screen bg-gray-100">
      <form className="bg-white p-8 rounded shadow-lg w-96 border-t-4 border-blue-500">
        <h2 className="text-2xl font-bold mb-6 text-center text-gray-800">Provider Login</h2>
        <input 
          type="email" placeholder="Email" className="w-full p-2 mb-4 border rounded focus:outline-blue-400"
          onChange={(e) => setFormData({...formData, email: e.target.value})} 
          required
        />
        <input 
          type="password" placeholder="Password" className="w-full p-2 mb-4 border rounded focus:outline-blue-400"
          onChange={(e) => setFormData({...formData, password: e.target.value})} 
          required
        />
        <GoogleLogin
            onSuccess={handleGoogleSuccess}
            onError={() => console.log('Login Failed')}
            useOneTap // Optional: Enables smooth one-tap prompt on page load
          />
        <p className="mt-4 text-sm text-center">
          Don't have an account? <span className="text-blue-500 cursor-pointer" onClick={() => navigate('/register')}>Register</span>
        </p>
      </form>
    </div>
  )
}

export default Login
